from __future__ import annotations
"""
Tenant service — business logic for tenant CRUD, API key rotation,
usage tracking, and plan management.
"""


import logging
import secrets
import uuid
from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from models.tenant import Tenant
from schemas.tenant import (
    TenantRegisterRequest,
    TenantResponse,
    TenantPublicResponse,
    TenantUsageResponse,
    TenantListResponse,
)

logger = logging.getLogger(__name__)


class TenantService:
    """All tenant-related business operations."""

    def __init__(self, session: AsyncSession) -> None:
        self.session = session

    # ── Create ─────────────────────────────────────────────────────────────────

    async def register(self, data: TenantRegisterRequest) -> Tenant:
        """
        Register a new tenant.
        Raises ValueError if subdomain is already taken.
        """
        # Check subdomain uniqueness
        existing = await self._get_by_subdomain(data.subdomain)
        if existing is not None:
            raise ValueError(f"Subdomain '{data.subdomain}' is already taken")

        tenant = Tenant(
            id=str(uuid.uuid4()),
            name=data.name,
            subdomain=data.subdomain.lower(),
            plan=data.plan,
            is_active=True,
            created_at=datetime.now(timezone.utc),
            settings=data.settings or {},
        )
        # api_key is generated by the model default
        self.session.add(tenant)
        await self.session.flush()
        await self.session.refresh(tenant)

        logger.info(f"New tenant registered: {tenant.subdomain} ({tenant.id})")
        return tenant

    # ── Read ───────────────────────────────────────────────────────────────────

    async def get_by_id(self, tenant_id: str) -> Optional[Tenant]:
        result = await self.session.execute(
            select(Tenant).where(Tenant.id == tenant_id)
        )
        return result.scalar_one_or_none()

    async def get_by_api_key(self, api_key: str) -> Optional[Tenant]:
        result = await self.session.execute(
            select(Tenant).where(Tenant.api_key == api_key)
        )
        return result.scalar_one_or_none()

    async def list_tenants(
        self,
        page: int = 1,
        limit: int = 20,
        active_only: bool = False,
    ) -> TenantListResponse:
        """Return a paginated list of tenants (admin use)."""
        stmt = select(Tenant)
        count_stmt = select(func.count(Tenant.id))

        if active_only:
            stmt = stmt.where(Tenant.is_active.is_(True))
            count_stmt = count_stmt.where(Tenant.is_active.is_(True))

        total_result = await self.session.execute(count_stmt)
        total = total_result.scalar_one()

        offset = (page - 1) * limit
        stmt = stmt.order_by(Tenant.created_at.desc()).offset(offset).limit(limit)
        result = await self.session.execute(stmt)
        tenants = list(result.scalars().all())

        return TenantListResponse(
            items=[TenantPublicResponse.model_validate(t) for t in tenants],
            total=total,
            page=page,
            limit=limit,
        )

    # ── Update ─────────────────────────────────────────────────────────────────

    async def update_settings(
        self, tenant_id: str, settings: dict
    ) -> Tenant:
        """Merge new settings into tenant.settings."""
        tenant = await self._get_or_404(tenant_id)
        existing = tenant.settings or {}
        tenant.settings = {**existing, **settings}
        await self.session.flush()
        await self.session.refresh(tenant)
        return tenant

    async def update_plan(self, tenant_id: str, plan: str) -> Tenant:
        tenant = await self._get_or_404(tenant_id)
        tenant.plan = plan
        await self.session.flush()
        await self.session.refresh(tenant)
        logger.info(f"Tenant {tenant_id} plan changed to {plan}")
        return tenant

    async def set_active(self, tenant_id: str, is_active: bool) -> Tenant:
        tenant = await self._get_or_404(tenant_id)
        tenant.is_active = is_active
        await self.session.flush()
        await self.session.refresh(tenant)
        return tenant

    async def rotate_api_key(self, tenant_id: str) -> Tenant:
        """Generate a new API key for the tenant (invalidates the old one)."""
        tenant = await self._get_or_404(tenant_id)
        tenant.regenerate_api_key()
        await self.session.flush()
        await self.session.refresh(tenant)
        logger.warning(f"API key rotated for tenant {tenant_id}")
        return tenant

    # ── Usage ──────────────────────────────────────────────────────────────────

    async def get_usage(self, tenant_id: str) -> TenantUsageResponse:
        """Return current usage stats vs plan limits."""
        tenant = await self._get_or_404(tenant_id)

        # Count customers and orders for this tenant
        from sqlalchemy import select, func
        from models.customer import Customer
        from models.order import Order

        cust_count_result = await self.session.execute(
            select(func.count(Customer.id)).where(Customer.tenant_id == tenant_id)
        )
        order_count_result = await self.session.execute(
            select(func.count(Order.id)).where(Order.tenant_id == tenant_id)
        )

        return TenantUsageResponse(
            tenant_id=tenant_id,
            plan=tenant.plan,
            limits=tenant.get_plan_limits(),
            usage={
                "customers": cust_count_result.scalar_one(),
                "orders": order_count_result.scalar_one(),
            },
        )

    # ── Private ────────────────────────────────────────────────────────────────

    async def _get_or_404(self, tenant_id: str) -> Tenant:
        tenant = await self.get_by_id(tenant_id)
        if tenant is None:
            raise ValueError(f"Tenant '{tenant_id}' not found")
        return tenant

    async def _get_by_subdomain(self, subdomain: str) -> Optional[Tenant]:
        result = await self.session.execute(
            select(Tenant).where(Tenant.subdomain == subdomain.lower())
        )
        return result.scalar_one_or_none()
