from __future__ import annotations
from typing import Dict, List, Optional, Any, Union
from typing import Dict, List, Optional, Any, Union
"""
Billing models for Stripe integration.

Subscription — tracks the tenant's Stripe subscription lifecycle.
Invoice       — local record of every Stripe invoice (for PDF generation, reporting).
"""


import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    String, DateTime, Integer, Boolean, Numeric, JSON,
    ForeignKey, func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from database import Base


def _uuid_str() -> str:
    return str(uuid.uuid4())


def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


class Subscription(Base):
    """Stripe subscription linked to a Tenant."""

    __tablename__ = "subscriptions"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid_str)

    tenant_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # Stripe identifiers
    stripe_customer_id: Mapped[Optional[str]] = mapped_column(String(255), unique=True, nullable=True)
    stripe_subscription_id: Mapped[Optional[str]] = mapped_column(String(255), unique=True, nullable=True, index=True)
    stripe_price_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)

    # Subscription state
    plan: Mapped[str] = mapped_column(String(50), nullable=False, default="basic")
    status: Mapped[str] = mapped_column(
        String(50), nullable=False, default="incomplete",
        # Possible values (mirror Stripe): incomplete, active, past_due, canceled, unpaid, trialing
    )
    trial_end: Mapped[datetime ] = mapped_column(DateTime(timezone=True), nullable=True)
    current_period_start: Mapped[datetime ] = mapped_column(DateTime(timezone=True), nullable=True)
    current_period_end: Mapped[datetime ] = mapped_column(DateTime(timezone=True), nullable=True)
    cancel_at_period_end: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    canceled_at: Mapped[datetime ] = mapped_column(DateTime(timezone=True), nullable=True)

    # Payment / billing
    amount_usd: Mapped[int] = mapped_column(Integer, default=0, nullable=False)  # cents
    currency: Mapped[str] = mapped_column(String(3), default="usd", nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now_utc, server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now_utc, onupdate=_now_utc, nullable=False
    )

    # Relationships
    tenant: Mapped["Tenant"] = relationship(  # noqa: F821
        "Tenant", back_populates="subscription", foreign_keys=[tenant_id]
    )
    invoices: Mapped[List["Invoice"]] = relationship(
        "Invoice", back_populates="subscription", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Subscription tenant={self.tenant_id[:8]} plan={self.plan} status={self.status}>"


class Invoice(Base):
    """Local copy of a Stripe invoice."""

    __tablename__ = "invoices"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid_str)

    subscription_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("subscriptions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    tenant_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)

    # Stripe
    stripe_invoice_id: Mapped[Optional[str]] = mapped_column(String(255), unique=True, nullable=True, index=True)
    stripe_payment_intent_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)

    # Invoice data
    invoice_number: Mapped[str] = mapped_column(String(50), nullable=False)
    status: Mapped[str] = mapped_column(String(30), nullable=False, default="draft")
    # Stripe statuses: draft, open, paid, uncollectible, void

    amount_due: Mapped[int] = mapped_column(Integer, nullable=False, default=0)   # cents
    amount_paid: Mapped[int] = mapped_column(Integer, nullable=False, default=0)  # cents
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="usd")

    period_start: Mapped[datetime ] = mapped_column(DateTime(timezone=True), nullable=True)
    period_end: Mapped[datetime ] = mapped_column(DateTime(timezone=True), nullable=True)
    due_date: Mapped[datetime ] = mapped_column(DateTime(timezone=True), nullable=True)
    paid_at: Mapped[datetime ] = mapped_column(DateTime(timezone=True), nullable=True)

    # PDF / hosted URL from Stripe
    hosted_invoice_url: Mapped[Optional[str]] = mapped_column(String(1024), nullable=True)
    invoice_pdf_url: Mapped[Optional[str]] = mapped_column(String(1024), nullable=True)

    # Local PDF path (generated by invoice_service)
    local_pdf_path: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)

    # Line items stored as JSON
    line_items: Mapped[Optional[List]] = mapped_column(JSON, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now_utc, server_default=func.now(), nullable=False
    )

    # Relationships
    subscription: Mapped["Subscription"] = relationship("Subscription", back_populates="invoices")

    def __repr__(self) -> str:
        return f"<Invoice {self.invoice_number} status={self.status} amount={self.amount_paid/100:.2f} {self.currency.upper()}>"
